### ISSUE TITLE
Faucet has no connection to the node. 

### ISSUE THREAD

**Issue by huhn511** [einfachiota/faucet.einfachIOTA.de#17]
Faucet Frontend should show an explained error message for faster problem solving. 

Error log:

```bash
Failed node https://comnet.einfachiota.de, One of the transaction inputs is used as output.
May 29 01:31:14 donations node[27715]: Error: All nodes failed
May 29 01:31:14 donations node[27715]:    One of the transaction inputs is used as output.
May 29 01:31:14 donations node[27715]:     at /home/gandalf/faucet.comnet.einfachiota.de/node_modules/@iota/client-load-balancer/dist/iota-client-load-balancer.js:172:39
May 29 01:31:14 donations node[27715]:     at step (/home/gandalf/faucet.comnet.einfachiota.de/node_modules/@iota/client-load-balancer/dist/iota-client-load-balancer.js:67:27)
May 29 01:31:14 donations node[27715]:     at Object.throw (/home/gandalf/faucet.comnet.einfachiota.de/node_modules/@iota/client-load-balancer/dist/iota-client-load-balancer.js:48
May 29 01:31:14 donations node[27715]:     at rejected (/home/gandalf/faucet.comnet.einfachiota.de/node_modules/@iota/client-load-balancer/dist/iota-client-load-balancer.js:39:69)
```

**Comment by Thoralf-M** [comment]
Fixed with this change
https://github.com/iota-pay/iota-payment-module/commit/1323db5f2e2fe5f8ce3da2cc5494c47ab32081f1

**Comment by Thoralf-M** [comment]
https://github.com/einfachiota/faucet.einfachIOTA.de/commit/73d2bdd1a8aa1ef8f903378daa4dc120c528accf
